name: deploy
 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: ["18.15.0"]
 
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
      redis:
        image: redis
        ports:
          - 6379:6379
 
    env:
      NODE_ENV: ci
      PORT: 3000
      GOOGLE_CLIENT_ID: 70265989829-0t7m7ce5crs6scqd3t0t6g7pv83ncaii.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 8mkniDQOqacXtlRD3gA4n2az
      MONGO_URI: mongodb://127.0.0.1:27017/adv-node-db
      COOKIE_KEY: 123123123
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: |
          npm install --legacy-peer-deps
          npm run build
      - name: Start server
        run: |
          nohup npm run start &
          sleep 3
      - name: Run tests
        run: npm run test
